version: "3"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ayane_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_DATABASE: ayane_dev
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 3306:3306

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
