version: "3"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ayane_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ayane_dev
    ports:
      - 3306:3306

  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
