service: ayane

useDotenv: true

plugins:
  - serverless-offline
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs18.x

  region: ap-northeast-1
  stage: dev

  memorySize: 128
  architecture: arm64
  timeout: 5

  logRetentionInDays: 7
  versionFunctions: false

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    STAGE: ${self:provider.stage}

    MYSQL_DATABASE_URL: ${env:MYSQL_DATABASE_URL}
    POSTGRES_DATABASE_URL: ${env:POSTGRES_DATABASE_URL}
    REDIS_URL: ${env:REDIS_URL}

    UPSTASH_REDIS_REST_URL: ${env:UPSTASH_REDIS_REST_URL}
    UPSTASH_REDIS_REST_TOKEN: ${env:UPSTASH_REDIS_REST_TOKEN}

package:
  patterns:
    - "!**"
    - "!node_modules/**"
    - output/package.json
    - output/handlers.js
    - output/handlers.js.map

functions:
  touch:
    handler: output/handlers.touch
    events:
      - schedule: cron(0 12 * * ? *)
  http:
    handler: output/handlers.http
    url: true
    events:
      - httpApi: "*"

custom:
  scriptHooks:
    # https://github.com/weixu365/serverless-scriptable-plugin/issues/49#issuecomment-594383342
    # serverless-offline 이전에 직접 빌드
    before:offline:start:init: pnpm run package
    before:package:createDeploymentArtifacts: pnpm run package
