service: ayane

useDotenv: true

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs18.x

  region: ap-northeast-1
  stage: dev

  memorySize: 256
  architecture: arm64

  logRetentionInDays: 1
  versionFunctions: false
  timeout: 5

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"

    STAGE: ${self:provider.stage}
    REDIS_URL: ${env:REDIS_URL}

    AYANE_PLANETSCALE_LABEL: ${env:AYANE_PLANETSCALE_LABEL}
    AYANE_PLANETSCALE_TYPE: ${env:AYANE_PLANETSCALE_TYPE}
    AYANE_PLANETSCALE_ARG_1: ${env:AYANE_PLANETSCALE_ARG_1}

    AYANE_SUPABASE_LABEL: ${env:AYANE_SUPABASE_LABEL}
    AYANE_SUPABASE_TYPE: ${env:AYANE_SUPABASE_TYPE}
    AYANE_SUPABASE_ARG_1: ${env:AYANE_SUPABASE_ARG_1}

    AYANE_REDISLAB_LABEL: ${env:AYANE_REDISLAB_LABEL}
    AYANE_REDISLAB_TYPE: ${env:AYANE_REDISLAB_TYPE}
    AYANE_REDISLAB_ARG_1: ${env:AYANE_REDISLAB_ARG_1}

    AYANE_UPSTASH_REDIS_LABEL: ${env:AYANE_UPSTASH_REDIS_LABEL}
    AYANE_UPSTASH_REDIS_TYPE: ${env:AYANE_UPSTASH_REDIS_TYPE}
    AYANE_UPSTASH_REDIS_ARG_1: ${env:AYANE_UPSTASH_REDIS_ARG_1}
    AYANE_UPSTASH_REDIS_ARG_2: ${env:AYANE_UPSTASH_REDIS_ARG_2}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:BatchWriteItem"
            - "dynamodb:Scan"
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/AyaneKeyValue

package:
  patterns:
    - "!**"
    - "!node_modules/**"
    - artifact/handlers.mjs*
    - views/**/*

functions:
  schedule:
    handler: artifact/handlers.schedule
    events:
      - schedule: cron(0 12 * * ? *)
  http:
    handler: artifact/handlers.http
    url: true
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{pathname+}

resources:
  Resources:
    KeyValueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AyaneKeyValue
        AttributeDefinitions:
          - AttributeName: label
            AttributeType: S
        KeySchema:
          - AttributeName: label
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  scriptHooks:
    # https://github.com/weixu365/serverless-scriptable-plugin/issues/49#issuecomment-594383342
    # serverless-offline 이전에 직접 빌드
    before:offline:start:init: pnpm bundle
    before:package:createDeploymentArtifacts: pnpm bundle
