service: ayane

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

  region: ap-northeast-1
  stage: dev

  memorySize: 128
  architecture: arm64

  logRetentionInDays: 7
  versionFunctions: false

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    STAGE: ${self:provider.stage}

functions:
  http:
    handler: src/handlers.http
    events:
      - httpApi: "*"

custom:
  esbuild:
    config: "./esbuild.config.cjs"
