service: ayane

useDotenv: true

plugins:
  - serverless-scriptable-plugin

provider:
  name: aws
  runtime: nodejs18.x

  region: ap-northeast-1
  stage: dev

  memorySize: 128
  architecture: arm64

  logRetentionInDays: 7
  versionFunctions: false

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    STAGE: ${self:provider.stage}

    MYSQL_DATABASE_URL: ${env:MYSQL_DATABASE_URL}
    POSTGRES_DATABASE_URL: ${env:POSTGRES_DATABASE_URL}
    REDIS_URL: ${env:REDIS_URL}

package:
  patterns:
    - "!**"
    - "!node_modules/**"
    - output/package.json
    - output/handlers.js

functions:
  touch:
    handler: output/handlers.touch
    events:
      - schedule: cron(0 12 * * ? *)

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: pnpm run package
